name: kooboo_app_cli
description: Kooboo app CLI for Flutter
version: 1.0.0
homepage: https://github.com/Ucoon/kooboo_app_cli.git

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  args: ^2.3.0
  ansicolor: ^2.0.1
  cli_util: ^0.3.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

executables:
  kapp: kooboo_app_cli
